export enum Method {
    POST="POST",
    GET="GET",
    PUT="PUT",
    DELETE="DELETE",
    GETBY="GETBY",
    GETPAGINATEDBY="GETPAGINATEDBY",
    GETPAGINATED="GETPAGINATED",
    GETBYLIMIT="GETBYLIMIT",
    GETWITHINTIME="GETWITHINTIME",
    GETSIZE="GETSIZE",
}